{{/* vim: set filetype=mustache: */}}

{{- include "common.deployment" (list . .Values .Values.autoscaling .Values.serviceAccount "<CHARTNAME>.deployment") }}

{{- define "<CHARTNAME>.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{- include "common.container" (append . "<CHARTNAME>.container") | nindent 8 }}
{{- end }}

{{- define "<CHARTNAME>.container" -}}
ports:
  - name: http
    containerPort: 80
    protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
{{- end }}
