{{/* vim: set filetype=mustache: */}}

{{- define "common.deployment.tpl" -}}
{{- $autoscaling := .Values.autoscaling | default (dict) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{ include "common.metadata" . | nindent 2 }}
spec:
  {{- if not $autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - {{- include "common.container" . | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}

{{- define "common.deployment" -}}
{{- include "common.utils.flattenCall" (list "common.utils.merge" . "common.deployment.tpl") -}}
{{- end -}}
