{{/* vim: set filetype=mustache: */}}

{{- define "common.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  {{ include "common.metadata" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end -}}

{{- define "common.service" -}}
{{- include "common.utils.flattenCall" (list "common.utils.merge" . "common.service.tpl") -}}
{{- end -}}
